<?php 
if (!defined('DP_BASE_DIR')) {
	die('You should not access this file directly.');
}
### Copyright (c) 2004, The dotProject Development Team dotproject.net and sf.net/projects/dotproject ###
### All rights reserved. Released under GPL License. For further Information see LICENSE ###

### CONFIGURATION FILE AUTOMATICALLY GENERATED BY THE DOTPROJECT INSTALLER ###
### FOR INFORMATION ON MANUAL CONFIGURATION AND FOR DOCUMENTATION SEE ./includes/config-dist.php ###

$dPconfig['dbtype'] = 'mysql';
$dPconfig['dbhost'] = 'db450420073.db.1and1.com';
$dPconfig['dbname'] = 'db450420073';
$dPconfig['dbprefix'] = 'dotp_';
$dPconfig['dbuser'] = 'dbo450420073';
$dPconfig['dbpass'] = '.M4SC4CH4pas!';
$dPconfig['dbpersist'] = false;
$dPconfig['root_dir'] = $baseDir;
$dPconfig['base_url'] = $baseUrl;
?>